#!/bin/bash
piccolo choice001.pi -o choice001
if [ "$#" -eq 1 ] && [ "$1" = "--with-valgrind" ]
then
  valgrind --leak-check=full --error-exitcode=2 --suppressions=../valgrind.supp ./choice001 > /dev/null 2> /dev/null
  if [ "$?" -ne 0 ]
  then
    exit 2
  fi
else
./choice001
fi
rm choice001
