#!/bin/bash
piccolo string004.pi -o string004
if [ "$#" -eq 1 ] && [ "$1" = "--with-valgrind" ]
then
  valgrind --leak-check=full --error-exitcode=2 --suppressions=../valgrind.supp ./string004 > /dev/null 2> /dev/null
  if [ "$?" -ne 0 ]
  then
    exit 2
  fi
else
./string004
fi
rm string004
