#!/bin/bash
piccolo basic001.pi -o basic001
if [ "$#" -eq 1 ] && [ "$1" = "--with-valgrind" ]
then
  valgrind --leak-check=full --error-exitcode=2 --suppressions=../valgrind.supp ./basic001 > /dev/null 2> /dev/null
  echo $?
  if [ "$?" -ne 0 ]
  then
    exit 2
  fi
else
./basic001
fi
rm basic001
