{-|
Module         : Back.RTOptions
Description    : Runtime options to pass to a compiled code
Stability      : experimental

In the future, this module should disappear since runtime options should be passed when compiling
the program generated by the piccolo compiler only. This will allow to not recompile a module
when trying to run a program with different runtime options (for example, changing the maximal number
of running threads).
-}
module Back.RTOptions where

-- | Runtime options contain some information to pass to the runtime system.
data RTOptions = RTOptions { nbThreads    :: Int  -- ^ number of running threads
                           , stdGCFuel    :: Int  -- ^ fuel value to determine when to call GC2
                           , quickGCFuel  :: Int  -- ^ fuel value to determine when to call GC
                           , activeFactor :: Int  -- ^ GC factor
                           }

-- | 'defaultsRTOptions' gives a standard version of runtime options.
defaultsRTOptions :: IO RTOptions
defaultsRTOptions = return $ RTOptions { nbThreads    = 4
                                       , stdGCFuel    = 42
                                       , quickGCFuel  = 42
                                       , activeFactor = 42
                                       }
