#!/bin/bash
piccolo lexprs003.pi -o lexprs003
if [ "$#" -eq 1 ] && [ "$1" = "--with-valgrind" ]
then
  valgrind --leak-check=full --error-exitcode=2 --suppressions=../valgrind.supp ./lexprs003 > /dev/null 2> /dev/null
  if [ "$?" -ne 0 ]
  then
    exit 2
  fi
else
./lexprs003
fi
rm lexprs003
