#!/bin/bash
piccolo basic002.pi -o basic002
if [ "$#" -eq 1 ] && [ "$1" = "--with-valgrind" ]
then
  valgrind --leak-check=full --error-exitcode=2 --suppressions=../valgrind.supp ./basic002 > /dev/null 2> /dev/null
  if [ "$?" -ne 0 ]
  then
    exit 2
  fi
else
./basic002
fi
rm basic002
