#!/bin/bash
piccolo lexprs001.pi -o lexprs001
if [ "$#" -eq 1 ] && [ "$1" = "--with-valgrind" ]
then
  valgrind --leak-check=full --error-exitcode=2 --suppressions=../valgrind.supp ./lexprs001 > /dev/null 2> /dev/null
  if [ "$?" -ne 0 ]
  then
    exit 2
  fi
else
./lexprs001
fi
rm lexprs001
